version: "3"
services:
  frontend:
    container_name: client-container
    build: ./fronted
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: server-container
    build: ./backend
    ports:
      - "4000:4000"
    

