version: "3"
services:
  frontend:
    image: node:alpine
    working_dir: /frontend
    environment:
      - API_URL=http://13.127.96.235:4000
    volumes: 
      - "./frontend:/frontend"
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  backend:
    image: node:alpine
    working_dir: /backend
    volumes:
      - "./backend:/backend"
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"

